# Generated by Django 5.2.9 on 2025-12-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_title', models.CharField(max_length=100)),
                ('jobs_link', models.URLField(max_length=500, unique=True)),
                ('jobs_addr', models.CharField(max_length=100)),
                ('jobs_type', models.CharField(max_length=100)),
                ('jobs_date', models.DateTimeField()),
                ('jobs_exp', models.CharField(max_length=100)),
                ('jobs_edu', models.CharField(max_length=100)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
        ),
    ]
